name: Main Deployment

on:
  push:
    branches: ["main"]

  workflow_dispatch:
jobs:
  check-changes:
    name: Check changes in folders
    runs-on: ubuntu-latest
    outputs:
      odoo: ${{ steps.filter.outputs.odoo }}
      flutter: ${{ steps.filter.outputs.flutter }}
      rasa: ${{ steps.filter.outputs.rasa }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            odoo:
              - 'backend/odoo/**'
            flutter:
              - 'frontend/**'
            rasa:
              - 'backend/rasa-engine/**'
      - name: Odoo Changes tests
        if: steps.filter.outputs.odoo == 'true'
        run: echo "Odoo Changes"
      - name: Flutter Changes tests
        if: steps.filter.outputs.flutter == 'true'
        run: echo "Flutter Changes"
      - name: Rasa Changes tests
        if: steps.filter.outputs.rasa == 'true'
        run: echo "Rasa Changes"
      - name: Odoo No Changes tests
        if: steps.filter.outputs.odoo != 'true'
        run: echo "Odoo No Changes"
      - name: Flutter No Changes tests
        if: steps.filter.outputs.flutter != 'true'
        run: echo "Flutter No Changes"
      - name: Rasa No Changes tests
        if: steps.filter.outputs.rasa != 'true'
        run: echo "Rasa No Changes"
  check-filters:
    name: Check changes in variables
    runs-on: ubuntu-latest
    needs: check-changes
    steps:
      - name: View Status
        run: echo "Result of test-app was '${{ needs.check-changes.result }}'"
        run: echo "Result of test-app was '${{ steps.check-changes.outcome }}'"
      - name: Odoo Changes tests
        if: needs.check-changes.outputs.odoo == 'true'
        run: echo "Odoo Changes 2"
      - name: Flutter Changes tests
        if: needs.check-changes.outputs.flutter == 'true'
        run: echo "Flutter Changes 2"
      - name: Rasa Changes tests
        if: needs.check-changes.outputs.rasa == 'true'
        run: echo "Rasa Changes 2"
      - name: Odoo No Changes tests
        if: needs.check-changes.outputs.odoo != 'true'
        run: echo "Odoo No Changes 2"
      - name: Flutter No Changes tests
        if: needs.check-changes.outputs.flutter != 'true'
        run: echo "Flutter No Changes 2"
      - name: Rasa No Changes tests
        if: needs.check-changes.outputs.rasa != 'true'
        run: echo "Rasa No Changes 2"